server.document-root = "/usr/share/skyaware/html"
server.port = 8080
server.modules = (
    "mod_alias",
    "mod_setenv"
)

mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png",
  ".js" => "application/javascript",
  ".css" => "text/css",
  ".json" => "application/json",
  ".svg" => "image/svg+xml",
  ".gif" => "image/gif",
  ".ico" => "image/x-icon"
)

index-file.names = ( "index.html" )

alias.url = (
  "/data/" => "/run/dump1090-fa/",
  "/skyaware/data/" => "/run/dump1090-fa/",
  "/skyaware/" => "/usr/share/skyaware/html/",
  "/" => "/usr/share/skyaware/html/"
)

$HTTP["url"] =~ "^.*\.json$" {
  setenv.set-response-header = ( "Access-Control-Allow-Origin" => "*" )
}
