server.document-root = "/usr/local/share/tar1090/html"
server.port = 8080
server.modules = (
    "mod_alias",
    "mod_setenv",
    "mod_deflate"
)

mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png",
  ".js" => "application/javascript",
  ".css" => "text/css",
  ".json" => "application/json",
  ".svg" => "image/svg+xml",
  ".gif" => "image/gif",
  ".ico" => "image/x-icon",
  ".gz" => "application/gzip",
  ".binCraft" => "application/octet-stream"
)

index-file.names = ( "index.html" )

alias.url = (
  "/tar1090/data/" => "/run/adsb-data/",
  "/tar1090/chunks/" => "/run/tar1090/",
  "/tar1090/aircraft_sil/" => "/usr/local/share/tar1090/aircraft_sil/",
  "/tar1090/" => "/usr/local/share/tar1090/html/",
  "/data/" => "/run/adsb-data/",
  "/chunks/" => "/run/tar1090/",
  "/aircraft_sil/" => "/usr/local/share/tar1090/aircraft_sil/",
  "/skyaware/data/" => "/run/adsb-data/",
  "/skyaware/" => "/usr/share/skyaware/html/",
  "/" => "/usr/local/share/tar1090/html/"
)

# CORS headers for json and chunk requests
$HTTP["url"] =~ "^/(data|chunks|tar1090/data|tar1090/chunks)/" {
  setenv.add-response-header = ( "Access-Control-Allow-Origin" => "*" )
}

# Gzip headers for chunk files generated by tar1090.sh
$HTTP["url"] =~ "(chunk_.*gz$|current_.*gz$)" {
  setenv.add-response-header = (
    "Access-Control-Allow-Origin" => "*",
    "Content-Encoding" => "gzip",
    "Content-Type" => "application/json"
  )
}

$HTTP["url"] =~ "(db-.*\.js$|\.binCraft$)" {
  setenv.add-response-header = (
    "Content-Encoding" => "gzip"
  )
}

$HTTP["url"] =~ "\.json$" {
  setenv.add-response-header = (
    "Cache-Control" => "no-cache",
    "Access-Control-Allow-Origin" => "*"
  )
}
